# Materials and Timetable {.unnumbered}

## Timetable {.unnumbered}
|Date|Session|Topics|Facilitator|
|:---|:------|:-----|:----------|
|Mon 27-03-2023|Morning session|Introduction to R and Rstudio|Liberty Mlambo|
|||Data types and structures|Dr Hakunawadi Pswarayi|
|1200-1300(GMT+1)||**Break**||
||Afternoon session|Data wrangling (with Chapter 7 homework)|Dr Chris Chagumaira|
|||||
|Tue 28-03-2023|Morning session|Developing custom functions in R|Liberty Mlambo|
|1200-1300(GMT+1)||**Break**||
||Afternoon session| Summary statistics and data visualization|Dr Hakunawadi Pswarayi|
|||||
|Wed 29-03-2023|Morning session|Basic Modelling in R|Prof Murray Lark|
|1200-1300(GMT+1)||**Break**||
|Wed 29-03-2023|Afternoon session|Basic Modelling in R (Cont..)|Prof Murray Lark|

## Materials {.unnumbered}

Please download the materials for the training from [here](https://dzvoti.github.io/mapsR/mapsR-Training.zip). Note that the mTaterials you downloaded are zipped folder which will require you to unzip it before you can access the files.

If you are using a Mac, you can unzip the folder by double clicking on the folder and then right clicking on the folder and selecting "Open with Archive Utility". If you are using a PC, you can unzip the folder by right clicking on the folder and selecting "Extract All".



